{
  description = ''
    Pure and reproducible, and possibly curated collection of wallpapers.
  '';

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    systems.url = "github:nix-systems/default";
  };

  outputs = {
    nixpkgs,
    systems,
    ...
  }: let
    inherit (nixpkgs) lib;

    genSystems = lib.genAttrs (import systems);
    pkgsFor = nixpkgs.legacyPackages;
  in {
    wallpapers = let
      fileExts = ["png" "jpg" "jpeg"];
    in
      builtins.map (n: let
        findFile = builtins.filter builtins.pathExists (map (ext: ./wallpapers/${n}.${ext}) fileExts);
        file =
          if findFile == []
          then builtins.throw "Either ${n} isn't a file or it doesn't have the ${builtins.concatStringsSep ", " (lib.lists.init fileExts)} or ${lib.lists.last fileExts} extensions."
          else builtins.head findFile;
      in {
        path = file;
        tags = lib.splitString "-" n;
        hash = builtins.hashFile "sha256" file;
      }) [
        "catppuccin-01"
        "catppuccin-02"
        "catppuccin-03"
        "catppuccin-04"
        "catppuccin-05"
        "catppuccin-06"
        "catppuccin-01"
        "catppuccin-02"
        "catppuccin-03"
        "catppuccin-04"
        "catppuccin-05"
        "catppuccin-06"
        "catppuccin-3d-model"
        "catppuccin-abandoned-trainstation"
        "catppuccin-abstract-swirls"
        "catppuccin-aesthetic"
        "catppuccin-astronaut"
        "catppuccin-atlantis"
        "catppuccin-aztec-mysteries"
        "catppuccin-bars"
        "catppuccin-base"
        "catppuccin-basement"
        "catppuccin-beach-path"
        "catppuccin-beach"
        "catppuccin-biking-sunset"
        "catppuccin-black-hole"
        "catppuccin-blue-kaiju"
        "catppuccin-blueprint"
        "catppuccin-bsod"
        "catppuccin-bunnies-road"
        "catppuccin-cabin-2"
        "catppuccin-cabin-4"
        "catppuccin-cabin-5"
        "catppuccin-cabin"
        "catppuccin-calder-moore-aliencrack"
        "catppuccin-car-2"
        "catppuccin-car-wreck"
        "catppuccin-castle"
        "catppuccin-cat-in-clouds"
        "catppuccin-cat-vibin"
        "catppuccin-cherry-2"
        "catppuccin-cherry-3"
        "catppuccin-cherry-4"
        "catppuccin-cherry-5"
        "catppuccin-cherry-6"
        "catppuccin-cherry"
        "catppuccin-chess-gate"
        "catppuccin-chinese-painting-1"
        "catppuccin-chinese-painting-2"
        "catppuccin-city-harbor"
        "catppuccin-city-horizon"
        "catppuccin-city-on-water"
        "catppuccin-city"
        "catppuccin-cliff-path"
        "catppuccin-cloud-coffee"
        "catppuccin-clouds-2"
        "catppuccin-clouds-3"
        "catppuccin-clouds-3"
        "catppuccin-clouds-5"
        "catppuccin-clouds-reflecting-on-sea"
        "catppuccin-clouds"
        "catppuccin-coffee-shop"
        "catppuccin-cold-alley"
        "catppuccin-cool"
        "catppuccin-corals-fish-underwater"
        "catppuccin-cottages-river"
        "catppuccin-crane"
        "catppuccin-dark-forest"
        "catppuccin-dark-star"
        "catppuccin-dark-waves"
        "catppuccin-day-forest-path"
        "catppuccin-deer-glade"
        "catppuccin-degirled"
        "catppuccin-diner-lonely-road"
        "catppuccin-dino"
        "catppuccin-dominik-mayer-1"
        "catppuccin-dominik-mayer-10"
        "catppuccin-dominik-mayer-11"
        "catppuccin-dominik-mayer-12"
        "catppuccin-dominik-mayer-13"
        "catppuccin-dominik-mayer-14"
        "catppuccin-dominik-mayer-15"
        "catppuccin-dominik-mayer-16"
        "catppuccin-dominik-mayer-17"
        "catppuccin-dominik-mayer-18"
        "catppuccin-dominik-mayer-19"
        "catppuccin-dominik-mayer-2"
        "catppuccin-dominik-mayer-20"
        "catppuccin-dominik-mayer-21"
        "catppuccin-dominik-mayer-22"
        "catppuccin-dominik-mayer-23"
        "catppuccin-dominik-mayer-3"
        "catppuccin-dominik-mayer-4"
        "catppuccin-dominik-mayer-5"
        "catppuccin-dominik-mayer-6"
        "catppuccin-dominik-mayer-7"
        "catppuccin-dominik-mayer-8"
        "catppuccin-dominik-mayer-9"
        "catppuccin-dragon"
        "catppuccin-droplets"
        "catppuccin-dwarf-saber"
        "catppuccin-excalibur-lake"
        "catppuccin-fantasy-city"
        "catppuccin-flower-field-2"
        "catppuccin-flower-field-3"
        "catppuccin-flower-field"
        "catppuccin-flower"
        "catppuccin-flowering-rain"
        "catppuccin-flying-comets-clouds"
        "catppuccin-fox-clearing"
        "catppuccin-fox"
        "catppuccin-galaxy-waves"
        "catppuccin-genshin-landscape"
        "catppuccin-gentlemen-sunset"
        "catppuccin-gingerbread-house"
        "catppuccin-girls-stars"
        "catppuccin-grandfather-tree"
        "catppuccin-grassy-well"
        "catppuccin-guy-majou"
        "catppuccin-harbor-3"
        "catppuccin-harbor"
        "catppuccin-haunted-house"
        "catppuccin-hollow-knight"
        "catppuccin-hollow-knight"
        "catppuccin-hollow"
        "catppuccin-horizon-2"
        "catppuccin-horizon"
        "catppuccin-i-touch-this"
        "catppuccin-idk-tbh"
        "catppuccin-isekai"
        "catppuccin-japan-alley"
        "catppuccin-jellyfish"
        "catppuccin-jupiter"
        "catppuccin-kaiju"
        "catppuccin-keyboard-2"
        "catppuccin-keyboard"
        "catppuccin-kitchen"
        "catppuccin-kitty"
        "catppuccin-knight-building"
        "catppuccin-koi"
        "catppuccin-kurzgezagt"
        "catppuccin-lantern-light-room"
        "catppuccin-laundry"
        "catppuccin-lelouch"
        "catppuccin-lightbulbs"
        "catppuccin-lighthouse-2"
        "catppuccin-lighthouse"
        "catppuccin-lovely-summer"
        "catppuccin-main-street"
        "catppuccin-map"
        "catppuccin-marine-tunnel"
        "catppuccin-mars-car"
        "catppuccin-mars"
        "catppuccin-math"
        "catppuccin-minimalist-black-hole"
        "catppuccin-misty-boat"
        "catppuccin-moon-beach"
        "catppuccin-moscow"
        "catppuccin-mountain-range"
        "catppuccin-mushishi"
        "catppuccin-my-neighbor-totoro-sunflowers"
        "catppuccin-native-ruins"
        "catppuccin-night-forest-path"
        "catppuccin-nix-tux"
        "catppuccin-ocean_with_cloud"
        "catppuccin-old-computer"
        "catppuccin-oversized-cat"
        "catppuccin-paint"
        "catppuccin-painting-standing"
        "catppuccin-painting"
        "catppuccin-panes"
        "catppuccin-pine"
        "catppuccin-pink-clouds"
        "catppuccin-pitstop"
        "catppuccin-pixel-alley"
        "catppuccin-pixel-car"
        "catppuccin-pixel-castle"
        "catppuccin-pixel-earth"
        "catppuccin-pixel-galaxy"
        "catppuccin-pixel-napping"
        "catppuccin-pixel-reading"
        "catppuccin-plane-purple"
        "catppuccin-platform"
        "catppuccin-pompeii"
        "catppuccin-puffy-stars"
        "catppuccin-purple-horizon"
        "catppuccin-purpled-night"
        "catppuccin-railroad-2"
        "catppuccin-railroad-horizon"
        "catppuccin-rainy-window"
        "catppuccin-red-city"
        "catppuccin-retro2_live"
        "catppuccin-river-city"
        "catppuccin-road"
        "catppuccin-rocket-launch"
        "catppuccin-rooftops"
        "catppuccin-ruins"
        "catppuccin-sakura-aura"
        "catppuccin-sakura-gate"
        "catppuccin-sakura-trees-over-river"
        "catppuccin-samurai"
        "catppuccin-satellite"
        "catppuccin-shiba-inu"
        "catppuccin-ship-2"
        "catppuccin-sky-railroad"
        "catppuccin-sky-sailing"
        "catppuccin-sky-ships"
        "catppuccin-sky"
        "catppuccin-snowflakes"
        "catppuccin-snowy-train"
        "catppuccin-soft-rose"
        "catppuccin-space-piano"
        "catppuccin-space"
        "catppuccin-space"
        "catppuccin-square-city"
        "catppuccin-stall"
        "catppuccin-street-4"
        "catppuccin-street"
        "catppuccin-subway"
        "catppuccin-sunken-tower"
        "catppuccin-sunset"
        "catppuccin-sushi"
        "catppuccin-swirls"
        "catppuccin-sword"
        "catppuccin-temple"
        "catppuccin-toast"
        "catppuccin-touhou-lake_catppuccin-mocha"
        "catppuccin-tower"
        "catppuccin-train-sideview"
        "catppuccin-train-station"
        "catppuccin-tree-2"
        "catppuccin-tree-optimism"
        "catppuccin-tree-stump"
        "catppuccin-tree"
        "catppuccin-trolley"
        "catppuccin-underwater-deep-blue-desktop-wallpaper"
        "catppuccin-van-chilling"
        "catppuccin-venice-market"
        "catppuccin-vibrant-gate"
        "catppuccin-village-gate"
        "catppuccin-voxel-city"
        "catppuccin-voxel-houses-monochrome"
        "catppuccin-wall"
        "catppuccin-wallhaven-9mjw78"
        "catppuccin-wallhaven-vqoo1p"
        "catppuccin-wanderer"
        "catppuccin-waterfall"
        "catppuccin-waves"
        "catppuccin-whale"
        "catppuccin-wheat"
        "catppuccin-windows-xp"
        "catppuccin-yohoho"
        "catppuccin-zuchold-archtecture"
        "cities-01"
        "cities-02"
        "cities-03"
        "cities-04"
        "cities-05"
        "cities-06"
        "cities-07"
        "cities-08"
        "cities-09"
        "cities-10"
        "cities-11"
        "cities-12"
        "cities-13"
        "cities-14"
        "gruvbox-01"
        "monochrome-01"
        "nature-01"
        "nature-02"
        "nature-03"
        "nature-04"
        "nature-05"
        "nature-06"
        "nature-07"
        "oxocarbon-01"
        "oxocarbon-02"
        "rose_pine-01"
        "rose_pine-02"
        "rose_pine-03"
        "rose_pine-04"
        "rose_pine-05"
        "rose_pine-06"
        "space-01"
        "space-02"
        "space-03"
        "space-04"
        "tokyo_night-01"
        "tokyo_night-02"
        "tokyo_night-03"
        "tokyo_night-04"
        "tokyo_night-05"
        "unorganized-01"
        "unorganized-02"
        "unorganized-03"
        "unorganized-04"
        "unorganized-05"
        "unorganized-06"
        "unorganized-07"
        "unorganized-08"
        "unorganized-09"
        "unorganized-10"
        "unorganized-11"
        "nord-01"
        "nord-02"
        "nord-03"
        "nord-04"
        "nord-05"
      ];

    packages = genSystems (_:
      builtins.listToAttrs (map (n: {
          name = n;
          value = throw "As of #15, wallpkgs no longer uses packages for wallpapers instead preferring to use the `wallpapers` flake output. Sorry for any inconvenience.";
        }) [
          "catppuccin"
          "oxocarbon"
          "unorganized"
          "tokyo_night"
          "space"
          "gruvbox"
          "rose_pine"
          "nature"
          "cities"
          "monochrome"
          "nord"
        ]));

    # I do not accept anything else.
    formatter = genSystems (system: pkgsFor.${system}.alejandra);
  };
}
