name: Generate Archives

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  create-archives:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create archives
        run: |
          mkdir -p archives
          for dir in wallpapers/*/; do
            base=$(basename "$dir")
            if [ "$base" != "unorganized" ]; then
              zip -r "archives/${base}.zip" "$dir"
            fi
          done

      - name: Copy assets
        run: |
          cp .github/assets/* ./archives

      - name: Upload to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./archives
